# Generated by Django 4.2.13 on 2024-09-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('icon', models.CharField(default='fas fa-code', max_length=50)),
                ('link', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
    ]
