# Generated by Django 4.2.13 on 2024-09-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_technology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=300)),
                ('description', models.TextField(max_length=300)),
                ('github_link', models.URLField(blank=True)),
                ('project_link', models.URLField(blank=True)),
                ('project_link_text', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='projects/')),
                ('technologies', models.ManyToManyField(to='portfolio.technology')),
            ],
            options={
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
