# Generated by Django 4.2.13 on 2024-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
